CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL
);

CREATE TABLE transactions(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
amount DECIMAL(10,2) NOT NULL,
description TEXT,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
user_id BIGINT,
type_id BIGINT,
type VARCHAR(20) NOT NULL,
CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id),
);